### PR TITLE
closes #2 Export Directory Path

### LINKED ISSUE #2: Cannot set export directory under Windows
The url from the FileDialog begins with file:///  Under linux, this can be fixed by removing file://  under windows, though, that leaves a / in front of the drive letter like this :   /C:\Temp  
Must differentiate between windows and other systems.

### PR DESCRIPTION
**Pull request by jeetee**
- Restoring the export directory using the OS-differentiator.
- Generalized retrieving of the path from the dialog by using a regex.

### CODE REVIEW

**Comment by JosephEoff** [comment]
Incorrectly strips leading / from directory name under Linux.  Please check the regex - I'm not good at them, so I'm not real clear on how it supposed to work.
When selecting the directory on a Linux system, I receive file:///home/joseph/Songs/jeeteeTest
This needs to be modified to /home/joseph/Songs/jeeteeTest

**Comment by jeetee** [comment]
This should fix it.
I misread the original issue report as linux paths only having a double slash instead of a triple one.

Replace now happens in two steps:
1. Remove `file://` as it is common for all platforms
2. Only remove next slash if it is directly followed by a single character, semicolon and another slash. This should filter out the Drive letters on windows.

The regex transforms `/C:/Users/jt/Music` into `C:/Users/jt/Music` but leaves `/home/whatever` as is.

**Comment by JosephEoff** [comment]
OK.  I'll check it this evening.

**Comment by JosephEoff** [comment]
Looks good on Windows.  I'll check on Linux later when I'm home.

**Comment by JosephEoff** [comment]
Works under Linux.

**Pull request merged**
