### PR TITLE
ported to MS3

### PR DESCRIPTION
**Pull request by jeetee**
it doesn't have access to the partNames yet, so those are numbered now.

### CODE REVIEW

**Comment by JosephEoff** [comment]
Hmm.  I don't think I want this in Master.  Not that there's something wrong with what you've done, I'd just rather keep the MuseScore2 Plugin separate from the MuseScore3 Plugin.

I'll have to set up a new project or repository for this.  Not tonight, though.  Got a couple of other things to finish up.

**Comment by JosephEoff** [comment]
I setup a new repository after all, and pulled your port into it.
Repository:
https://github.com/JosephEoff/MuseScore_UltraStar_Exporter_MS3

**Comment by jeetee** [comment]
Fair enough. That was fast!
For my plugins I move the current "master" to a 2.x branch and update master to 3, assuming that some fixes/additional features will apply to both. Whatever floats your boat :)

**Comment by jeetee** [comment]
Will you update https://musescore.org/en/project/ultrastar-export-plugin with additional links to the 3.x version, or do you wish me to do so?

**Comment by JosephEoff** [comment]
I'll update the links when I'm on my PC.  Tomorrow afternoon, probably.

**Pull request closed without merging**
